/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "on-primary": "#004a2d",
        "inverse-surface": "#fcf8f9",
        "on-error": "#490106",
        "inverse-on-surface": "#565556",
        "tertiary-container": "#84fdbc",
        "on-secondary-container": "#c1bfba",
        "surface-container": "#19191b",
        "secondary-dim": "#9f9e99",
        "secondary-fixed-dim": "#d6d4cf",
        "surface-dim": "#0e0e0f",
        "on-tertiary-fixed": "#004b2e",
        "tertiary-fixed": "#84fdbc",
        "inverse-primary": "#006d44",
        "on-primary-fixed": "#00492c",
        "on-error-container": "#ff9993",
        "surface-container-high": "#1f1f22",
        "primary-dim": "#54ce91",
        "on-tertiary-fixed-variant": "#006b43",
        "on-tertiary": "#006a42",
        "on-secondary": "#20201d",
        "primary": "#64dd9e",
        "outline": "#767578",
        "on-background": "#e7e5e8",
        "secondary-container": "#3b3c38",
        "on-tertiary-container": "#00603c",
        "on-primary-fixed-variant": "#006942",
        "surface": "#0e0e0f",
        "primary-container": "#005232",
        "on-secondary-fixed-variant": "#5c5c57",
        "on-secondary-fixed": "#3f403c",
        "surface-tint": "#64dd9e",
        "error": "#ee7d77",
        "secondary-fixed": "#e4e2dc",
        "on-surface-variant": "#acaaae",
        "tertiary-dim": "#75eeae",
        "primary-fixed": "#81fab9",
        "error-container": "#7f2927",
        "tertiary": "#ceffdf",
        "secondary": "#9f9e99",
        "surface-bright": "#2b2c2f",
        "error-dim": "#bb5551",
        "tertiary-fixed-dim": "#75eeae",
        "on-primary-container": "#6ee7a8",
        "surface-container-low": "#131315",
        "outline-variant": "#48484b",
        "surface-variant": "#252628",
        "surface-container-highest": "#252628",
        "on-surface": "#e7e5e8",
        "primary-fixed-dim": "#73ebab",
        "background": "#0e0e0f"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Syne", "sans-serif"],
        "body": ["DM Sans", "sans-serif"],
        "label": ["DM Mono", "monospace"],
        "brand": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
